baseURL = "https://nitelang.github.io"
publishDir = "../nitelang.github.io"
title = "Nite Lang"
enableRobotsTXT = true
# this example loads the theme as hugo module
[module]
[[module.imports]]
  path = 'github.com/onweru/compose'
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = ["https://github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
#theme = "compose"
#enableGitInfo = true ## disable for now because no repo set / uploaded to track

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]
